* Todo Projectile (formerly =org-project=)
  =todo-projectile= compiles all of the =TODO=, =FIXME=, =NOTE= and =XXX=
  occurences from a project into a single org file (stored at the project root)
  with links to each of the occurences. It depends on projectile for it's project
  information. This will not work without projectile

** Functions
   - =todo-projectile/open-project= - Opens an existing project (using completing read).

   - =todo-projectile/update-and-open-project= - Similar to the above command but also re-indexes
     the project file to reflect any changes you've made.

** Customization
  - =todo-projectile-use-ag= - Use ag for project searching rather than the default grep.
    - *Values*: =t= or =nil=
    - *Default*: =nil=

  - =todo-projectile--search-regexp= - The regex used to search through the projects for match.
    - *Values*: [elisp regexp]
    - *Default*: =TODO|FIXME|NOTE|XXX=

  - =todo-projectile--grep-args= - The arguments that =todo-projectile= passes to =grep= when it's looking
    for files. *WARNING*: Changing this from the default can break =todo-projectile= as it relies on
    certain options being used.
    - *Values*: [list of strings]
    - *Default*: =("--extended-regexp" "--dereference-recursive" "--files-with-matches" "--no-messages" "--color=never")=

  - =todo-projectile--ag-args= - Same as above command except for =ag= rather than =grep=. Same warning applies.
    - *Values*: [list of strings]
    - *Default*: =("--files-with-matches" "--nocolor")=

  - =todo-projectile--file-name= - The name of the file that =todo-projectile= will store the =TODO=s
    in. By default this file is stored at the project root.
    - *Values*: [any valid filename]
    - *Default*: =.project.org=

** Issues
   If you find any issues or have any ideas/feedback please open an issue. I'll do my best to resolve it.
